#!/usr/bin/env bash
set -e

FILES_LOC="~/.local/state/locs"
LOG="$FILES_LOC/log"
UNI="$FILES_LOC/uni"
ACTIVE="$FILES_LOC/active"
QUICK="$FILES_LOC/quicklist"

# Goto a uni directory
uni () {
  cd "~/uni/$(cat $UNI|fzf)"
}

projects () {
  cd "~/dev/proj/"
  cd "$(for i in $(cat $ACTIVE;ls -d */;ls -d neovim/*;ls -d emacs/*);do echo $i;done|fzf)"
}

quicklist () {
  cd "$(cat $QUICK|fzf)"
}

walk () {
  cd "$HOME"
  cd "$(fd -type d|fzf)"
}

update_loc () {
  cd "$2"
  # Remove from uni file
  # cat "$1" > "$1.bak"

  # SED pattern is just to remove trailing | generated by for loop
  # TODO Does not preserve previous entries
  cat "$1" | grep -Ev \
   "$(for i in $(cat $1|fzf -m --prompt '(removing)> ');\
      do printf '%s|' $i;done|sed 's/\/|$/\//')" > "$1"
  # Add new directories
  fd --type d | fzf -m --prompt '(adding)> ' >> "$1"
}

update_uni () {
  update_loc "$UNI" "~/uni/"
}

update_quick () {
  update_loc "$QUICK" "$HOME"
}

case "$1" in
  1) 
    uni
    ;;
  2) 
    projects
    ;;
  3)
    quicklist
    ;;
  4)
    walk
    ;;
  5)
    update_uni
    ;;
  6)
    update_quick
    ;;
  *) echo "Wrong Argument"
    ;;
esac


