-- TODO: Add plugin mini.files for quick file navigation
-- TODO: Add dadbod package for db interface (https://github.com/tpope/vim-dadbod)
-- TODO: add keybinds to scroll telescope preview
-- TODO: add keybinds to expand telescope preview to a tmp buffer.
